[project]
name = "bb"
dynamic = ["version"]
description = "Work seamlessly with BitBucket from the command line."
authors = [
    {name = "psadi", email = "adithya3494@gmail.com"},
]
dependencies = [
    "typer[all]>=0.7.0",
    "xdg>=5.1.1",
    "requests>=2.28.2",
    "pyperclip>=1.8.2",
]
requires-python = ">=3.7"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
bb = "bb:_bb"

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
version = { source = "file", path = "bb/__version__.py" }

[tool.pdm.build]
includes = ["bb"]
excludes = ["tests"]

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.2.1",
    "tox>=4.4.5",
    "pytest-cov>=4.0.0",
    "tox-pdm>=0.6.1",
    "mypy>=1.0.1",
    "ruff>=0.0.254",
]

[tool.pdm.scripts]
bb = { call = "bb:_bb" }

[tool.ruff]
ignore = ["E501"]
